---
driver:
  name: vagrant

provisioner:
  name: chef_zero
<% if ENV.key?('CHEF_VERSION') %>
  require_chef_omnibus: <%= ENV['CHEF_VERSION'].sub(/^.*> (.*)[.][0-9]+$/, '\1') %>
<% else %>
  require_chef_omnibus: true
<% end %>

platforms:
- name: centos-6
- name: centos-7
- name: debian-7.8
- name: fedora-27
# FreeBSD platform requires to run kitchen verify twice by hand
# - name: freebsd-9.2
# - name: freebsd-10.0
- name: opensuse-leap-42
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: ubuntu-18.04

suites:
- name: default
  run_list:
  - recipe[ssh_authorized_keys_test::default]
