rvm:
- 2.0.0
- 2.1
- 2.2

sudo: false

env:
- CHEF_VERSION="~> 11.0"
- CHEF_VERSION="~> 12.0"

matrix:
  exclude:
  # Gem::InstallError: chef-zero requires Ruby version >= 2.1.0
  - rvm: 2.0.0
    env: CHEF_VERSION="~> 12.0"

bundler_args: --without doc integration integration_cloud guard

script:
- bundle exec rake travis:ci
